#
# A Makefile for cards.lib
# (c) osFree project
#

DESCRIPTION     = Cards support library
TARGET_CLASS    = LIBRARY
TARGET_SUBCLASS = STATIC
LICENSE         = LicenseRef-PD-2

!include $(%ROOT)tools/mk/build.mk
