#
# A Makefile for LOGO.LGO
# (c) osFree project,
# author, date
#

PROJ        = logo
#TRGT        = $(PROJ).lgo
srcfiles    = $(p)logo$(e)
JWASM       = 1
RAW         = 1
EXT         = lgo
NOLIBS      = 1
ADD_ASMOPT  = -I=$(MYDIR)..$(SEP)..$(SEP)..$(SEP)..$(SEP)macrolib
DEST        = os2$(SEP)mdos$(SEP)winos2

!include $(%ROOT)tools/mk/appsdos.mk

