#
# A main Makefile for WIN16
# (c) osFree project,
# author
#

DIRS = alloc atom bitmap class clipboard combo comm16 dce &
       dialog dosmem file filedlg listbox mapping &
       msg printdlg profile socket16 str sys sysdir text timer

# infosize   - missed structure. Seems to be win9x api?

!include $(%ROOT)tools/mk/all.mk

