#
# A Makefile for lzexpand.dll
# (c) osFree project,
# author, date
#

PROJ     = main
TRGT     = $(PROJ).dll
DESC     = Main CPL
srcfiles = $(p)main$(e)
# linking dll file
DLL     = 1
EXPORTS = CPlApplet       .1

DEST = os2$(SEP)mdos$(SEP)winos2$(SEP)system

!include $(%ROOT)tools/mk/appsw16.mk
