#
# A Makefile for osFree Janus Paint
# (c) osFree project
#

DESCRIPTION = osFree Janus Paint
TARGET_VERSION = 310
SOURCES = paint canvas toolbox palette textedit clipboard file tools

ADD_COPT = -sg

EXPORTS = MainWndProc, CanvasWndProc, PaletteWndProc, TextEdit_SubclassProc, OpenDlgProc, SaveDlgProc, ColorDlgProc, ToolboxWndProc

!include $(%ROOT)tools/mk/build.mk

