#
# A Makefile for osFree Janus Paint
# (c) osFree project
#

DESCRIPTION = Janus Paint
TARGET_VERSION = 310

EXPORTS = MainWndProc, CanvasWndProc, PaletteWndProc, TextEdit_SubclassProc, OpenDlgProc, SaveDlgProc, ColorDlgProc, ToolboxWndProc

!include $(%ROOT)tools/mk/build.mk

