#define FaceColor (GetSysColor(COLOR_BTNFACE))
#define HandColor (GetSysColor(COLOR_WINDOWTEXT))
#define TickColor (GetSysColor(COLOR_WINDOWTEXT))
#define ShadowColor (GetSysColor(COLOR_BTNSHADOW ))
#define BackgroundColor (GetSysColor(COLOR_BTNFACE))
