#
# A Makefile for cards.dll
# (c) osFree project
#

DESCRIPTION  = Janus Cards API Library
TARGET_CLASS = LIBRARY
ADD_COPT     = -dCARDSTYLE_DEFAULT
ADD_RCOPT    = -dCARDSTYLE_DEFAULT

EXPORTS = &
	WEP.1, &
	cdtAnimate.2, &
	cdtDraw.3, &
	cdtDrawExt.4, &
	cdtInit.5, &
	cdtTerm.6

!include $(%ROOT)tools/mk/build.mk
