#
# A main Makefile for Win16 applications
# (c) osFree project,
# valerius, 2006/10/30
#


DIRS = shared calc clipbrd clock notepad pifedit progman sysedit taskman winhelp winmine winver reversi pbrush control

!include $(%ROOT)tools/mk/all.mk

