#
# A Makefile for osFree diagnostic tool
# (c) osFree project
#

DESCRIPTION = osFree Diagnostic tools
TARGET_API  = DOS
SOURCES     = common globals system lowlevel main init run help page00 scrprint
JWASM       = 1
LIBS        = dos_shared

!include $(%ROOT)tools/mk/build.mk
