#
# A Makefile for WIN.COM
# (c) osFree project
#

PROJ       = win
DESC       = Windows Loader
srcfiles   = $(p)execlogo$(e)
JWASM      = 1
COM        = 1
EXT        = cnf
NOLIBS     = 1
DEST       = os2$(SEP)mdos$(SEP)winos2$(SEP)system
ADD_ASMOPT = -I=$(MYDIR)..$(SEP)..$(SEP)macrolib

!include $(%ROOT)tools/mk/appsdos.mk


