#
# A Makefile for shell.lib
# (c) osFree project
#

DESC     = Janus Shell API Library
#srcfiles = $(p)GlobalData$(e) $(p)About$(e) $(p)Environment$(e) $(p)AtomEx$(e) $(p)Strings$(e) $(p)Shell$(e) $(p)Registry$(e) $(p)DragDrop$(e) $(p)Exec$(e) $(p)Hook$(e) # $(p)Icon$(e)
TARGET_CLASS = LIBRARY
TARGET_SUBCLASS = STATIC
  

DEST = os2$(SEP)mdos$(SEP)winos2$(SEP)system

!include $(%ROOT)tools/mk/build.mk

