#
# A Makefile for shell.lib
# (c) osFree project
#

DESCRIPTION     = Janus Shell API Library
TARGET_CLASS    = LIBRARY
TARGET_SUBCLASS = STATIC
LICENSE         = LGPL-2.1-or-later

DEST = os2$(SEP)mdos$(SEP)winos2$(SEP)system

!include $(%ROOT)tools/mk/build.mk

