#
# A Makefile for osFree Janus Reversi
# (c) osFree project
#

DESCRIPTION = osFree Janus Reversi
TARGET_API=WIN

ADD_COPT = -sg
EXPORTS =WndProc, dpProdInfo, dpEve

!include $(%ROOT)tools/mk/build.mk


