#
# A Makefile for cards.lib
# (c) osFree project
#

PROJ      = cards
TARGET_API = WIN
TARGET_CLASS = LIBRARY
TARGET_SUBCLASS = STATIC
SOURCES = cardbitmaps cardcolor cardcount cardlib cardrgndraw cardstack cardbutton cardregion cardrgnmouse cardwindow dropzone

!include $(%ROOT)tools/mk/build.mk
