#
# A Makefile for EXIT_VDM
# (c) osFree project,
# author, date
#

PROJ      = msd
TRGT      = $(PROJ).exe
DESC      = osFree Diagnostic
srcfiles  = $(p)infoplus$(e)

ADD_COPT  = -i=$(MYDIR)..$(SEP)..$(SEP)include
ADD_LINKOPT = lib $(BLD)lib$(SEP)dos_shared.lib

!include $(%ROOT)tools/mk/appsdos.mk
