#if 0
#define VK_LBUTTON       0x01 //    Left mouse button.
#define VK_RBUTTON       0x02 //    Right mouse button.
#define VK_CANCEL        0x03 //    Used for control-break processing.
#define VK_MBUTTON       0x04 //    Middle mouse button (3-button mouse).
#define VK_BACK          0x08 //    
#define VK_TAB           0x09 //    
#define VK_CLEAR         0x0C //    
#define VK_RETURN        0x0D //    
#define VK_SHIFT         0x10 //    
#define VK_CONTROL       0x11 //    
#define VK_MENU          0x12 //    
#define VK_PAUSE         0x13 //    
#define VK_CAPITAL       0x14 //    
#define VK_ESCAPE        0x1B //    
#define VK_SPACE         0x20 //    
#define VK_PRIOR         0x21 //    Page up.
#define VK_NEXT          0x22 //    Page down.
#define VK_END           0x23 //    
#define VK_HOME          0x24 //    
#define VK_LEFT          0x25 //    
#define VK_UP            0x26 //    
#define VK_RIGHT         0x27 //    
#define VK_DOWN          0x28 //    
#define VK_SELECT        0x29 //    
#define VK_PRINT         0x2A //    Only used by Nokia.
#define VK_EXECUTE       0x2B //    Never used.
#define VK_SNAPSHOT      0x2C //    SYSREQ key starting with Windows 3.0.
#define VK_INSERT        0x2D //    
#define VK_DELETE        0x2E //    
#define VK_HELP          0x2F //    
#endif                    
#define VK_0             0x30 //    
#define VK_1             0x31 //    
#define VK_2             0x32 //    
#define VK_3             0x33 //    
#define VK_4             0x34 //    
#define VK_5             0x35 //    
#define VK_6             0x36 //    
#define VK_7             0x37 //    
#define VK_8             0x38 //    
#define VK_9             0x39 //    
#define VK_A             0x41 //    
#define VK_B             0x42 //    
#define VK_C             0x43 //    
#define VK_D             0x44 //    
#define VK_E             0x45 //    
#define VK_F             0x46 //    
#define VK_G             0x47 //    
#define VK_H             0x48 //    
#define VK_I             0x49 //    
#define VK_J             0x4A //    
#define VK_K             0x4B //    
#define VK_L             0x4C //    
#define VK_M             0x4D //    
#define VK_N             0x4E //    
#define VK_O             0x4F //    
#define VK_P             0x50 //    
#define VK_Q             0x51 //    
#define VK_R             0x52 //    
#define VK_S             0x53 //    
#define VK_T             0x54 //    
#define VK_U             0x55 //    
#define VK_V             0x56 //    
#define VK_W             0x57 //    
#define VK_X             0x58 //    
#define VK_Y             0x59 //    
#define VK_Z             0x5A //    
#if 0                     
#define VK_NUMPAD0       0x60 //    
#define VK_NUMPAD1       0x61 //    
#define VK_NUMPAD2       0x62 //    
#define VK_NUMPAD3       0x63 //    
#define VK_NUMPAD4       0x64 //    
#define VK_NUMPAD5       0x65 //    
#define VK_NUMPAD6       0x66 //    
#define VK_NUMPAD7       0x67 //    
#define VK_NUMPAD8       0x68 //    
#define VK_NUMPAD9       0x69 //    
#define VK_MULTIPLY      0x6A //    
#define VK_ADD           0x6B //    
#define VK_SEPARATER     0x6C //    Never generated by keyboard driver.
#define VK_SUBTRACT      0x6D //    
#define VK_DECIMAL       0x6E //    
#define VK_DIVIDE        0x6F //    
#define VK_F1            0x70 //    
#define VK_F2            0x71 //    
#define VK_F3            0x72 //    
#define VK_F4            0x73 //    
#define VK_F5            0x74 //    
#define VK_F6            0x75 //    
#define VK_F7            0x76 //    
#define VK_F8            0x77 //    
#define VK_F9            0x78 //    
#define VK_F10           0x79 //    
#define VK_F11           0x7A //    
#define VK_F12           0x7B //    
#define VK_F13           0x7C //    
#define VK_F14           0x7D //    
#define VK_F15           0x7E //    
#define VK_F16           0x7F //    
#define VK_F17           0x80 //    
#define VK_F18           0x81 //    
#define VK_F19           0x82 //    
#define VK_F20           0x83 //    
#define VK_F21           0x84 //    
#define VK_F22           0x85 //    
#define VK_F23           0x86 //    
#define VK_F24           0x87 //    
#define VK_NUMLOCK       0x90 //   NUMLOCK on all keyboards.
#endif                    
#define VK_OEM_SCROLL    0x91 //   SCROLL LOCK on all keyboards.
#define VK_OEM_1         0xBA //   Punctuation.
#define VK_OEM_PLUS      0xBB //   Punctuation.
#define VK_OEM_COMMA     0xBC //   Punctuation.
#define VK_OEM_MINUS     0xBD //   Punctuation.
#define VK_OEM_PERIOD    0xBE //   Punctuation.
#define VK_OEM_2         0xBF //   Punctuation.
#define VK_OEM_3         0xC0 //   Punctuation.
#define VK_OEM_4         0xDB //   Punctuation.
#define VK_OEM_5         0xDC //   Punctuation.
#define VK_OEM_6         0xDD //   Punctuation.
#define VK_OEM_7         0xDE //   Punctuation.
#define VK_OEM_8         0xDF //   Punctuation.
//#define VK_F17         0xE0 //   F17 key on Olivetti extended keyboard (internal use only).
//#define VK_F18         0xE1 //   F18 key on Olivetti extended keyboard (internal use only).
#define VK_OEM_102       0xE2 //   < or | on IBM-compatible 102 enhanced keyboard (non-U.S.).
#define VK_ICO_HELP      0xE3 //   Help key on Olivetti extended keyboard (internal use only).
#define VK_ICO_00        0xE4 //   00 key on Olivetti extended keyboard (internal use only).
#define VK_ICO_CLEAR     0xE6 //   Olivetti extended keyboard (internal use only).
#define VK_OEM_RESET     0xE9 //   Only used by Nokia.
#define VK_OEM_JUMP      0xEA //   Only used by Nokia.
#define VK_OEM_PA1       0xEB //   Only used by Nokia.
#define VK_OEM_PA2       0xEC //   Only used by Nokia.
#define VK_OEM_PA3       0xED //   Only used by Nokia.
#define VK_OEM_WSCTRL    0xEE //   Only used by Nokia.
#define VK_OEM_CUSEL     0xEF //   Only used by Nokia.
#define VK_OEM_ATTN      0xF0 //   Only used by Nokia.
#define VK_OEM_FINNISH   0xF1 //   Only used by Nokia.
#define VK_OEM_COPY      0xF2 //   Only used by Nokia.
#define VK_OEM_AUTO      0xF3 //   Only used by Nokia.
#define VK_OEM_ENLW      0xF4 //   Only used by Nokia.
#define VK_OEM_BACKTAB   0xF5 //   Only used by Nokia.
#define VK_ATTN          0xF6 //   
#define VK_CRSEL         0xF7 //   
#define VK_EXSEL         0xF8 //   
#define VK_EREOF         0xF9 //   
#define VK_PLAY          0xFA //   
#define VK_ZOOM          0xFB //   
#define VK_NONAME        0xFC //   
#define VK_PA1           0xFD //   
#define VK_OEM_CLEAR     0xFE //   
