#
# A Makefile for osFree Janus Calculator
# (c) osFree project
#

DESCRIPTION = osFree Janus Calculator
TARGET_VERSION = 310
SOURCES = stats winecalc

ADD_COPT =  -dDEBUG=0

!include $(%ROOT)tools/mk/build.mk
