#
# A main Makefile for WIN16
# (c) osFree project,
# author
#

DIRS = us be bll br bul ca cr cz cz1 da dv fc fi fr gr hu hu1 ic it la ne no pl pl1 po ro ru se sf sg sl sl1 sp sv sw uk usx ycc ycl


!include $(%ROOT)tools/mk/all.mk

