#
# A Makefile for osFree Janus Program Manager
# (c) osFree project
#

DESCRIPTION = osFree Janus Program Manager
TARGET_VERSION = 310
SOURCES = dialog group grpfile main program string

ADD_RCOPT = -i=$(%WATCOM)$(SEP)h$(SEP)win

!include $(%ROOT)tools/mk/build.mk

