#
# A Makefile for osFree Janus Program Manager
# (c) osFree project
#

DESCRIPTION = Janus Program Manager
TARGET_VERSION = 310
EXCLUDE_LICENSE = README.MD TODO

ADD_RCOPT = -i=$(%WATCOM)$(SEP)h$(SEP)win

!include $(%ROOT)tools/mk/build.mk

