#
# A Makefile for DOSX
# (c) osFree project,
# author, date
#

PROJ       = dosx
TRGT       = $(PROJ).exe
DESC       = 286 MS-DOS Extender
srcfiles   = $(p)dosx$(e)
JWASM      = 1
DEST       = os2$(SEP)mdos$(SEP)winos2$(SEP)system
ADD_ASMOPT = -I=$(MYDIR)..$(SEP)..$(SEP)macrolib

DIRS = hdpmi

DIRS = hdpmi

!include $(%ROOT)tools/mk/appsdos.mk
