#
# A Makefile for osFree Janus Cardfile
# (c) osFree project
#

DESCRIPTION = osFree Janus Cardfile
SOURCES = main cardfile
EXPORTS = FileOpenDlgProc, SearchDlgProc, AddDlgProc, IndexDlgProc, AboutDlgProc

!include $(%ROOT)tools/mk/build.mk

