#
# A Makefile for osFree Janus Cardfile
# (c) osFree project
#

DESCRIPTION = osFree Janus Cardfile
SOURCES = main cardfile
TARGET_API = WIN
EXPORTS = FileOpenDlgProc, SearchDlgProc, AddDlgProc, IndexDlgProc, AboutDlgProc

ADD_COPT = -sg

!include $(%ROOT)tools/mk/build.mk

