#
# A Makefile for osFree Janus Cardfile
# (c) osFree project
#

DESCRIPTION = Janus Cardfile
EXPORTS = FileOpenDlgProc, SearchDlgProc, AddDlgProc, IndexDlgProc, AboutDlgProc

!include $(%ROOT)tools/mk/build.mk

