#
# A main Makefile for shared WIN16 libs
# (c) osFree project
#

DIRS = setupinf nlsapi cards # mfc

#PROJECT         = win_shared
#TARGET_API      = WIN
#TARGET_CLASS    = LIBRARY
#TARGET_SUBCLASS = STATIC
#LIBRARIES       = nlsapi cardlib

!include $(%ROOT)tools/mk/all.mk

