#
# A main Makefile for shared WIN16 libs
# (c) osFree project
#

DIRS     = setupinf nlsapi cardlib # mfc

PROJECT         = win_shared
TARGET_API      = WIN
TARGET_CLASS    = LIBRARY
TARGET_SUBCLASS = STATIC
LIBRARIES       = nlsapi cards

!include $(%ROOT)tools/mk/build.mk

