#
# A main Makefile for shared WIN16 libs
# (c) osFree project
#

DIRS = setupinf nlsapi cards shell # mfc

PROJECT         = win_shared
DESCRIPTION     = Win16 shared library
TARGET_API      = WIN
TARGET_CLASS    = LIBRARY
TARGET_SUBCLASS = STATIC
LIBRARIES       = nlsapi cards
LICENSE         = BSD-3-clause

!include $(%ROOT)tools/mk/build.mk

