#
# Makefile for NLS API lib
#

DESCRIPTION     = NLS API library
TARGET_CLASS    = LIBRARY
TARGET_SUBCLASS = STATIC
LICENSE         = BSD-3-clause
ADD_COPT = -I=$(MYDIR)..$(SEP)..$(SEP)include -DSTATIC
LIBS = setupinf

!include $(%ROOT)tools/mk/build.mk

