#
# A Makefile for LOGO.LGO
# (c) osFree project,
# author, date
#

PROJ  = xlat855
srcfiles    = $(p)xlat855$(e)
JWASM       = 1
RAW         = 1
NOLIBS      = 1
ADD_ASMOPT  = -I=$(MYDIR)..
DEST        = os2$(SEP)mdos$(SEP)winos2$(SEP)system

!include $(%ROOT)tools/mk/appsdos.mk

