#
# Makefile for setupinf lib
#

DESCRIPTION     = SETUP.INF parser
TARGET_CLASS    = LIBRARY
TARGET_SUBCLASS = STATIC
LICENSE         = BSD-3-clause

ADD_COPT = -I=$(MYDIR)..$(SEP)..$(SEP)include

!include $(%ROOT)tools/mk/build.mk

