#
# Makefile for common shared libs
#

PROJ = setupinf
TARGET_API = WIN
TARGET_CLASS = LIBRARY
TARGET_SUBCLASS = STATIC
SOURCES = setupinf string_utils inf_country inf_language inf_keyboard
ADD_COPT = -I=$(MYDIR)..$(SEP)..$(SEP)include

!include $(%ROOT)tools/mk/build.mk

