#
# A Makefile for LOGO.LGO
# (c) osFree project,
# author, date
#

PROJ  = xlat437
srcfiles    = $(p)xlat437$(e)
JWASM       = 1
RAW         = 1
NOLIBS      = 1
#INSTALL_ADD = 1
#ADD_ASMOPT  = -I=$(MYDIR)..$(SEP)..$(SEP)..$(SEP)..$(SEP)macrolib
DEST        = os2$(SEP)mdos$(SEP)winos2$(SEP)system

!include $(%ROOT)tools/mk/appsdos.mk

#TARGETS = $(PATH)xlat437.bin

#$(PATH)$(PROJ1).bin: $(PATH)$(PROJ).com
# @$(CP) $(PATH)$(PROJ).com $(PATH)$(PROJ1).bin $(BLACKHOLE)
