#
# A Makefile for osFree Janus Control Panel
# (c) osFree project
#

DIRS=applets

DESCRIPTION = osFree Janus Control Panel
EXPORTS = MainWndProc

# defines additional options for C compiler
ADD_COPT = -I=$(MYDIR)..$(SEP)..$(SEP)include

!include $(%ROOT)tools/mk/build.mk

