#
# A main Makefile for Win16 applications
# (c) osFree project,
# valerius, 2006/10/30
#


DIRS = calc clipbrd clock expand notepad pifedit progman sysedit taskman winhelp winmine winver

!include $(%ROOT)tools/mk/all.mk

